#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

system_type=$(uname -s)
system_arch=$(uname -m)

function is_osx() {
    [ "$system_type" = "Darwin" ] && return 0 || return 1
}
function is_wsl() {
    [ -n "$WSL_DISTRO_NAME" ] && return 0 || return 1
}
function is_linux() {
    [ "$system_type" = "Linux" ] && return 0 || return 1
}

if is_wsl; then
    for sock in "$HOME/.gnupg/S.gpg-agent" "/run/user/$UID/gnupg/S.gpg-agent"; do
        rm -f "$sock"
    done
    unset sock
    rm -f "$HOME/.ssh/agent.sock"

    if command -v wslpath >/dev/null && command -v wslvar >/dev/null; then
        [ -x "$HOME/.wsl-cmds/gpg" ] || ln -sf "$(wslpath "$(wslvar 'ProgramFiles(x86)')/GnuPG/bin/gpg.exe")" "$HOME/.wsl-cmds/gpg"

        [ -x "$HOME/.wsl-cmds/scp" ] || ln -sf "$(wslpath "$(wslvar 'SystemRoot')/System32/OpenSSH/scp.exe")" "$HOME/.wsl-cmds/scp"
        [ -x "$HOME/.wsl-cmds/sftp" ] || ln -sf "$(wslpath "$(wslvar 'SystemRoot')/System32/OpenSSH/sftp.exe")" "$HOME/.wsl-cmds/sftp"
        [ -x "$HOME/.wsl-cmds/ssh" ] || ln -sf "$(wslpath "$(wslvar 'SystemRoot')/System32/OpenSSH/ssh.exe")" "$HOME/.wsl-cmds/ssh"
        [ -x "$HOME/.wsl-cmds/ssh-add" ] || ln -sf "$(wslpath "$(wslvar 'SystemRoot')/System32/OpenSSH/ssh-add.exe")" "$HOME/.wsl-cmds/ssh-add"
    fi
fi

env RUNZSH="no" sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
if [ -f ".zshrc.pre-oh-my-zsh" ]; then
  mv ".zshrc.pre-oh-my-zsh" ".zshrc"
fi

echo "Init submodules"
yadm submodule update --recursive --init

rm -rf ".oh-my-zsh/custom/plugins"
ln -sf "../../.zsh-plugins" ".oh-my-zsh/custom/plugins"
if is_osx; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  echo "Updating homebrew bundle"
  brew bundle --global
fi

if is_linux; then
  sudo apt-get install --no-install-recommends -yyq \
    build-essential \
    cmake \
    curl \
    direnv \
    fonts-noto-color-emoji \
    mono-complete \
    php-cli \
    python3-dev \
    scdaemon \
    socat \
    vim-gtk3 \
    zsh \
  ;

  sudo snap install --classic --channel=16/stable node
  sudo snap install --classic go
  sudo snap install --classic hub
  sudo snap install --classic powershell

  sudo snap install --channel=extended hugo

  if [ ! -d "$HOME/bin" ]; then
    mkdir -p "$HOME/bin"
  fi

fi


pushd "$HOME/bin/emsdk"
  ./emsdk update-tags
  ./emsdk install latest
  ./emsdk activate latest
popd

pushd "$HOME/.rbenv"
  ./src/configure && make -C src
popd

composer_sigfile="$(mktemp)"
curl -L -s -o "$composer_sigfile" "https://composer.github.io/installer.sig"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

EXPECTED_SIGNATURE="$(cat "$composer_sigfile")"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]; then
    php composer-setup.php --quiet --install-dir="$HOME/bin" --filename=composer
fi
rm composer-setup.php

curl -o "$HOME/bin/wp" https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x "$HOME/bin/wp"

vim +BundleInstall +qall

pushd "$HOME/.vim/bundle/YouCompleteMe"
python3 install.py --all
popd

echo "Importing GPG key"
gpg --keyserver keys.openpgp.org --recv-keys 4C9CBFAD0069D6799660BCD540C2D9580349ED21

echo "Decrypting private files"
yadm decrypt

if is_wsl; then
  mkdir -p "$(wslpath "$(wslvar USERPROFILE)")/.ssh"
  cp "$HOME/.ssh/id_rsa" "$(wslpath "$(wslvar USERPROFILE)")/.ssh/"
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:diddledani/dotfiles.git"

