#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

mkdir -p $HOME/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/vundle
vim +BundleInstall +qall

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

if [ "$system_type" = "Linux" ]; then

  sudo apt install -yyq build-essential cmake python3-dev mono-complete
  sudo snap install --channel=8/stable node
  sudo snap install dotnet-sdk
  sudo snap install go

fi

pushd "$HOME/.vim/bundle/YouCompleteMe"
python3 install.py --cs-completer --go-completer
popd

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:diddledan/dotfiles.git"
