#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  echo "Updating homebrew bundle"
  brew bundle --global

  /usr/local/bin/emcc
  sed -i -e "s|\(^LLVM_ROOT = os.path.expanduser(os.getenv('LLVM',\) '/usr/bin'\()).*\)$|\1
  '/usr/local/opt/emscripten/libexec/llvm/bin'\2|;s|^\(BINARYEN_ROOT\)|#\1|" $HOME/.emscripten

fi

if [ "$system_type" = "Linux" ]; then

  sudo apt install -yyq \
    build-essential \
    curl \
    cmake \
    php-cli \
    python3-dev \
    mono-complete \
    vim \
  ;

  sudo snap install --classic --channel=10/stable node
  sudo snap install --classic dotnet-sdk
  sudo snap install --classic go
  sudo snap install --classic hub

  curl -L -s -o /tmp/emscripten.tgz "https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz"
  tar zxf /tmp/emscripten.tgz -C "$HOME/bin"

  pushd "$HOME/bin/emsdk-portable"
  ./emsdk update
  ./emsdk install latest
  ./emsdk update latest
  popd
fi

git clone https://github.com/rbenv/rbenv.git "$HOME/.rbenv"
pushd "$HOME/.rbenv"
src/configure && make -C src
popd

composer_sigfile="$(mktemp)"
curl -L -s -o "$composer_sigfile" "https://composer.github.io/installer.sig"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

EXPECTED_SIGNATURE="$(cat "$composer_sigfile")"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]; then
    php composer-setup.php --quiet --install-dir="$HOME/bin" --filename=composer
fi
rm composer-setup.php

mkdir -p $HOME/.vim/bundle
git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
vim +BundleInstall +qall

pushd "$HOME/.vim/bundle/YouCompleteMe"
python3 install.py --cs-completer --go-completer
popd

echo "Importing GPG key"
gpg --recv-keys 0349ED21

echo "Decrypting private files"
yadm decrypt

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:diddledan/dotfiles.git"

